# Generated by Django 5.1.3 on 2024-12-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='ID Card Image'),
        ),
    ]
