# Generated by Django 5.1.3 on 2024-12-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_id_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card_image',
        ),
    ]
