# Generated by Django 4.1.1 on 2022-10-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcherprofile',
            old_name='myUser',
            new_name='researcher',
        ),
    ]
