# Generated by Django 4.1.1 on 2022-10-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorprofile_verified_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='verified_admin',
            field=models.BooleanField(null=True),
        ),
    ]
