# Generated by Django 4.1.1 on 2022-10-31 08:57

from django.db import migrations, models
import django.db.models.deletion
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('modality', models.CharField(choices=[('X-ray', 'X-ray'), ('CT-scan', 'CT-scan'), ('MRI', 'MRI'), ('UltraSound', 'Ultrasound')], default='X-ray', max_length=30)),
                ('diagonised', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('img', models.ImageField(null=True, upload_to=doctor.models.get_upload_path)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patientprofile')),
            ],
        ),
    ]
