# Generated by Django 4.1.1 on 2022-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_diseasedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetails',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
