# Generated by Django 4.1.1 on 2022-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_diseasedetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasedetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
