# Generated by Django 4.1.1 on 2022-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctorprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetails',
            name='organ',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
