# Generated by Django 4.1.1 on 2022-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_diseasedetails_organ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetails',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
