# Generated by Django 4.1.1 on 2022-11-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_diseasedetails_modality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='otp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_phone',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
