# Generated by Django 4.1.1 on 2022-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctorprofile_otp_doctorprofile_verified_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='country_code',
            field=models.CharField(default='91', max_length=2),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='country_code',
            field=models.CharField(default='91', max_length=2),
        ),
    ]
