# Generated by Django 4.1.1 on 2022-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_doctorprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
