# Generated by Django 4.1.1 on 2022-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_researcherprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='verified_phone',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
