# Generated by Django 4.1.1 on 2022-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_researcherprofile_verified_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
