# Generated by Django 5.1.3 on 2024-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_alter_doctorprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='id_image',
            field=models.ImageField(default='', upload_to='researcherprofile'),
        ),
    ]
