# Generated by Django 5.1.3 on 2024-12-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_researcherprofile_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetails',
            name='age',
            field=models.BigIntegerField(default=0, max_length=4),
        ),
    ]
