# Generated by Django 5.1.3 on 2024-12-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_diseasedetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetails',
            name='alcohol',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=4),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='blood_oxygen_saturation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='cholesterol_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='chronic_kidney',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=4),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='diastolic_blood_pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='electrolyte_level',
            field=models.CharField(choices=[('BALANCED', 'BALANCED'), ('UNBALANCED', 'UNBALANCED')], default='Yes', max_length=15),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='heart_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='physically_inactive',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=4),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='smoking',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=4),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='stress',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=4),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='sugar_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='systolic_blood_pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diseasedetails',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseasedetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
